
//import com.sun.glass.events.KeyEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author EvMcQ5970
 */
public class Main extends javax.swing.JFrame {
    
    //Variables
    int cardNum = 0;
    
    int chur = 5;
    int pop = 5;
    int army = 5;
    int mon = 5;
    
    
    // Special conditions
    
    
    //Constructors
    Game thisGame = new Game(cardNum, chur, pop, army, mon);
    Write save = new Write();//chur, army, pop, mon, cardNum, "src\\data\\slot1"
    Read load = new Read();
    
    //Arrays
    //Option 1
    int[] chur1 = {0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    int[] pop1 = {0, 1, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    int[] army1 = {0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    int[] mon1 = {0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    
    //Option 2
    int[] chur2 = {0, -1, -3, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    int[] pop2 = {0, -1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    int[] army2 = {0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    int[] mon2 = {0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                    0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    
    //Conversations
    String[] toYou = {"Intro", "My Queen, the peasants are complaining about a food shortage."
                    , "My Queen, we wish to mine a nearby mountain, but the church says it is holy ground.",
                    "My Queen, the church believes there is a witch amongst your subjects",
                    " ", " ", " ", " ", " ", " ", " ", " ",
                    " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ",
                    " ", " ", " ", " "};
    String[] ans1 = {"Got it", "Increase funding for farmers.",
                    "Leave it be! Do you wish to anger the Gods?",
                    "Burn the witch!", " ", " ", " ", " ", " ", " ", " ", " ",
                    " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ",
                    " ", " ", " ", " "};
    String[] ans2 = {"Cool", "Who cares?", "Ignore the church, we need those metals.",
                    "Don't you touch them!", " ", " ", " ", " ", " ", " ", " ", " ",
                    " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ",
                    " ", " ", " ", " "};
    
    
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG = new javax.swing.JPanel();
        TopPanel = new javax.swing.JPanel();
        stat1 = new javax.swing.JLabel();
        stat2 = new javax.swing.JLabel();
        stat3 = new javax.swing.JLabel();
        stat4 = new javax.swing.JLabel();
        TextPanel = new javax.swing.JPanel();
        text = new javax.swing.JLabel();
        LeftOptionPanel = new javax.swing.JPanel();
        op1 = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        RightOptionPanel = new javax.swing.JPanel();
        op2 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BG.setBackground(new java.awt.Color(41, 26, 57));

        TopPanel.setBackground(new java.awt.Color(101, 66, 105));

        stat1.setFont(new java.awt.Font("Pristina", 1, 36)); // NOI18N
        stat1.setForeground(new java.awt.Color(255, 255, 255));
        stat1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stat1.setText("5");

        stat2.setFont(new java.awt.Font("Pristina", 1, 36)); // NOI18N
        stat2.setForeground(new java.awt.Color(255, 255, 255));
        stat2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stat2.setText("5");

        stat3.setFont(new java.awt.Font("Pristina", 1, 36)); // NOI18N
        stat3.setForeground(new java.awt.Color(255, 255, 255));
        stat3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stat3.setText("5");

        stat4.setFont(new java.awt.Font("Pristina", 1, 36)); // NOI18N
        stat4.setForeground(new java.awt.Color(255, 255, 255));
        stat4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stat4.setText("5");

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(stat1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stat2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(stat3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(stat4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stat1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stat2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stat3, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                    .addComponent(stat4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        TextPanel.setBackground(new java.awt.Color(101, 66, 105));
        TextPanel.setBorder(new javax.swing.border.SoftBevelBorder(0));

        text.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        text.setForeground(new java.awt.Color(255, 255, 255));
        text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text.setText("Intro\n");
        text.setToolTipText("");

        javax.swing.GroupLayout TextPanelLayout = new javax.swing.GroupLayout(TextPanel);
        TextPanel.setLayout(TextPanelLayout);
        TextPanelLayout.setHorizontalGroup(
            TextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TextPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TextPanelLayout.setVerticalGroup(
            TextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TextPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LeftOptionPanel.setBackground(new java.awt.Color(101, 66, 105));
        LeftOptionPanel.setBorder(new javax.swing.border.SoftBevelBorder(0));

        op1.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        op1.setForeground(new java.awt.Color(255, 255, 255));
        op1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        op1.setText("Got it");
        op1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                op1KeyPressed(evt);
            }
        });

        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CrownIconSmall.png"))); // NOI18N
        img1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LeftOptionPanelLayout = new javax.swing.GroupLayout(LeftOptionPanel);
        LeftOptionPanel.setLayout(LeftOptionPanelLayout);
        LeftOptionPanelLayout.setHorizontalGroup(
            LeftOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftOptionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LeftOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(op1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(img1))
                .addContainerGap())
        );
        LeftOptionPanelLayout.setVerticalGroup(
            LeftOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftOptionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(op1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(img1)
                .addContainerGap())
        );

        RightOptionPanel.setBackground(new java.awt.Color(101, 66, 105));
        RightOptionPanel.setBorder(new javax.swing.border.SoftBevelBorder(0));

        op2.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        op2.setForeground(new java.awt.Color(255, 255, 255));
        op2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        op2.setText("Cool");

        img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CrownIconSmall.png"))); // NOI18N
        img2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout RightOptionPanelLayout = new javax.swing.GroupLayout(RightOptionPanel);
        RightOptionPanel.setLayout(RightOptionPanelLayout);
        RightOptionPanelLayout.setHorizontalGroup(
            RightOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightOptionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RightOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(op2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightOptionPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(img2)))
                .addContainerGap())
        );
        RightOptionPanelLayout.setVerticalGroup(
            RightOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightOptionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(op2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(img2)
                .addContainerGap())
        );

        javax.swing.GroupLayout BGLayout = new javax.swing.GroupLayout(BG);
        BG.setLayout(BGLayout);
        BGLayout.setHorizontalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BGLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(BGLayout.createSequentialGroup()
                        .addComponent(LeftOptionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RightOptionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        BGLayout.setVerticalGroup(
            BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGLayout.createSequentialGroup()
                .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(BGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LeftOptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RightOptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void op1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_op1KeyPressed
        // TODO add your handling code here:

//        if (evt.getKeyCode()==KeyEvent.VK_LEFT){
//            
//            System.out.println("TO THE LEFT");
//            
//        }
//        public void KeyPressed(KeyEvent e) {
//            
//        }
        
        
        
    }//GEN-LAST:event_op1KeyPressed

    private void img1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img1MouseClicked
        // TODO add your handling code here:
        
        System.out.println("Left");
        
        //Assignment      
        assignLeft();
        
        //Check values (OutOfBounds, cardNum, Misc conditions)
        //Continue if nothing flags
        checkAndContinue();
        
    }//GEN-LAST:event_img1MouseClicked
    
    
    
    
    
    private void img2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img2MouseClicked
        // TODO add your handling code here:
        
        System.out.println("Right");
        
        //Assignment
        assignRight();
        
        //Check values (OutOfBounds, cardNum, Misc conditions)
        //Continue if nothing flags
        checkAndContinue();
        
        
    }//GEN-LAST:event_img2MouseClicked
    
    
    
    
    
    public void assignLeft(){
        
        //New values
        chur = thisGame.assignChur(chur, chur1[cardNum]);
        pop = thisGame.assignPop(pop, pop1[cardNum]);
        army = thisGame.assignArmy(army, army1[cardNum]);
        mon = thisGame.assignMon(mon, mon1[cardNum]);
        
        //Change in gui
        stat1.setText("" + chur);
        stat2.setText("" + pop);
        stat3.setText("" + army);
        stat4.setText("" + mon);
          
    }
    
    public void assignRight(){
        
        //New values
        chur = thisGame.assignChur(chur, chur2[cardNum]);
        pop = thisGame.assignPop(pop, pop2[cardNum]);
        army = thisGame.assignArmy(army, army2[cardNum]);
        mon = thisGame.assignMon(mon, mon2[cardNum]);
        
        //Change in gui
        stat1.setText("" + chur);
        stat2.setText("" + pop);
        stat3.setText("" + army);
        stat4.setText("" + mon);
        
    }
    
    public void checkAndContinue(){
    
    //Different game enders
        if (chur >= 10){
            // Church thinks you're a saint, you're not, you starve
            text.setText("The church, believing you to be a saint, has you"
                    + " undergo ");
            op1.setText("");
            op2.setText("");
            
        } else if (pop >= 10) {
            // Fans storm castle and you are trampled
            text.setText("");
            op1.setText("");
            op2.setText("");
            
        } else if (army >= 10) {
            // Army grows restless, you are overthrown and beheaded
            text.setText("");
            op1.setText("");
            op2.setText("");
            
            
        } else if (mon >= 10) {
            // Invaded by other nation, they were attracted to your great wealth
            text.setText("");
            op1.setText("");
            op2.setText("");
            
        } else if (chur <= 0) {
            // You are deemed a heretic, and burned at the stake
            text.setText("");
            op1.setText("");
            op2.setText("");
            
        } else if (pop <= 0) {
            // People hate you, you are dragged out of your castle and stoned
            text.setText("");
            op1.setText("");
            op2.setText("");
            
        } else if(army <= 0) {
            // Other nation takes advantage of weakness, you are pillaged
            text.setText("");
            op1.setText("");
            op2.setText("");
            
        } else if (mon <= 0) {
            // Starving and cold, your subjects die off one by one
            text.setText("Starving and cold, your subjects die off one by"
                    + " one until you yourself succumb to famine");
            op1.setText("");
            op2.setText("");
            
        } else if (cardNum >= 30) {
            //You win! Having reached the end of your life you die a good ruler
            
            
        } else {
            //Advance
            
            advance();
            
        }
    
    
}
    
    
    public void advance(){
        
        cardNum++;
        text.setText(toYou[cardNum]);
        op1.setText(ans1[cardNum]);
        op2.setText(ans2[cardNum]);
        
    }
    
    
    public void save(){
        
        save.writeTest(chur, army, pop, mon, cardNum, "src\\data\\slot1");
        
    }
    
    public void load(){
        
        
        
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG;
    private javax.swing.JPanel LeftOptionPanel;
    private javax.swing.JPanel RightOptionPanel;
    private javax.swing.JPanel TextPanel;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel op1;
    private javax.swing.JLabel op2;
    private javax.swing.JLabel stat1;
    private javax.swing.JLabel stat2;
    private javax.swing.JLabel stat3;
    private javax.swing.JLabel stat4;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
